version: "3"

services:
  jupyter:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --allow-root
    volumes:
      - .:/code
